### ISSUE TITLE
Should support SRV records with service discovery

### ISSUE THREAD

**Issue by JonRoma** [techservicesillinois/terraform-aws-ecs-service#11]
<a href="https://github.com/JonRoma"><img src="https://avatars2.githubusercontent.com/u/7817366?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [JonRoma](https://github.com/JonRoma)**
_Wednesday Jul 11, 2018 at 18:43 GMT_
_Originally opened as https://github.com/cites-illinois/as-aws-modules/issues/52_

----

This is useful for bridge mode, but the ecs-service module does not support yet. Does Terraform have what it needs to do this?

**Comment by evanjtravis** [comment]
tfvars:
```
cluster = "example"
launch_type = "EC2"
load_balancer = {
  container_name = "fargate",
  container_port = "80",
  host_header = "fargate-example.as-test.techservices.illinois.edu",
  name = "private",
  port = "80"
}
name = "delete-me-behave-tf-6GBQY4TAV4"
service_discovery = {
  namespace_id = "ns-pomsm4cehdoviesw",
  type = "SRV"
}
task_definition = {
  network_mode = "bridge"
}
```
With the above tvfars configuration, I was able to successfully apply the `aws-ecs-service.all` resource. The `service_discovery.type` defaults to "A", but I set it to "SRV" instead.

Should we have the default value for this variable be "SRV" as opposed to "A"?

**Comment by ddriddle** [comment]
@JonRoma @evanjtravis Taking a quick look at the AWS docs I think that we can safely default to using SRV records. In fact, I'm not sure why you would use anything else:

> If the task definition your service task specifies uses the awsvpc network mode, you can create any combination of A or SRV records for each service task. If you use SRV records, a port is required.
>
> If the task definition that your service task specifies uses the bridge or host network mode, an SRV record is the only supported DNS record type. Create an SRV record for each service task. The SRV record must specify a container name and container port combination from the task definition.
>
> If the task definition that your service task specifies uses the bridge or host network mode, only type SRV records are supported. Choose a container name and port combination to associate with the record.
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-discovery.html

In another doc it says:

> If the task definition that your service task specifies uses the awsvpc network mode, select either the A or SRV record type. If the type A DNS record is selected, skip to the next step. If the type SRV is selected, specify either the port that the service can be found on or a container name and port combination to associate with the record.
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-configure-servicediscovery.html

Given what the documentation says I think we should only support SRV records. Before we make the switch though I think it behooves us to test that this works as expected.

**Comment by evanjtravis** [comment]
The containers.join file used in the test:

```
        Given terraform file 'containers.json'
            """
            [{
              "name": "fargate",
              "image": "httpd",
              "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                  "awslogs-stream-prefix": "prod",
                  "awslogs-group": "example",
                  "awslogs-region": "us-east-2"
                }
              },
              "portMappings": [
                {
                  "containerPort": 80
                }
              ]
            }]
            """
```

**Comment by JonRoma** [comment]
So much has changed since this issue was created; not worth further effort.
