### ISSUE TITLE
public-sd/fargate example -- server is not coming up

### ISSUE THREAD

**Issue by JonRoma** [techservicesillinois/terraform-aws-ecs-service#14]
<a href="https://github.com/cmaturi"><img src="https://avatars1.githubusercontent.com/u/8779379?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cmaturi](https://github.com/cmaturi)**
_Thursday Aug 09, 2018 at 16:42 GMT_
_Originally opened as https://github.com/cites-illinois/as-aws-modules/issues/70_

----

Created the ecs service. Name --  fargate-sd
When tried to ping the server ith the following command
`$ curl fargate.discover.as-test.techservices.illinois.edu`
Receiving the following error
`curl: (6) Could not resolve host: fargate.discover.as-test.techservices.illinois.edu`
Found out that the tasks are being stopped because of the time out issue. (Timeout waiting for service discovery instance provisioning to complete.)

**Comment by JonRoma** [comment]
<a href="https://github.com/ddriddle"><img src="https://avatars2.githubusercontent.com/u/10728345?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ddriddle](https://github.com/ddriddle)**
_Friday Aug 10, 2018 at 01:05 GMT_

----

@cmaturi the config was bad. It was pointing at the wrong namespace. After the fix it still does not work :-( The reason being is that the DNS record returns the private IP address of the container instead of the public IP. Not sure why or how to fix it.

I will add that the private service discovery examples work great.

**Comment by ddriddle** [comment]
@cmaturi @JonRoma ECS does _NOT_ support public namespaces. See the service discovery [documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-discovery.html):

> * The Create Service workflow in the Amazon ECS console only supports registering services into private DNS namespaces. When a AWS Cloud Map private DNS namespace is created, a Route 53 private hosted zone will be created automatically.
> * Amazon ECS does not support registering services into public DNS namespaces.
> https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-discovery.html#service-discovery-considerations

@JonRoma can you please remove the `public-sd` examples since they are invalid and unsupported? When you have done this please close this ticket.

**Comment by ddriddle** [comment]
@JonRoma looking at the GUI I am beginning to doubt the documentation... First the GUI does allow the selection of public namespaces. Could you try manually creating an ECS service that uses a public namespace and see if it works? I am curious.

**Comment by JonRoma** [comment]
Example code isn't part of this repository, and there's no use case that merits attention to this ancient issue.
