### ISSUE TITLE
Service discovery fails on apply in bridge mode

### ISSUE THREAD

**Issue by ddriddle** [techservicesillinois/terraform-aws-ecs-service#16]
Scenario _Instance of 'aws_ecs_service' 'all'_ in file [as-aws-modules/test/features/ecs-service/ecs-service.feature](https://github.com/techservicesillinois/as-aws-modules/blob/test/ecs-service/test/features/ecs-service/ecs-services.feature) fails with the following error:
```
Error: Error applying plan:
1 error(s) occurred:
* aws_ecs_service.all: 1 error(s) occurred:
* aws_ecs_service.all: InvalidParameterException: When specifying 'host' or 'bridge' for networkMode, values for 'containerName' and 'containerPort' must be specified from the task definition. Registry: arn:aws:servicediscovery:us-east-2:224588347132:service/srv-l2ijonw3ungcigcj
        status code: 400, request id: 34d40946-e9ba-11e8-bdb8-9b87bd765b46 "delete-me-behave-tf-IHSKR34F3D" 
```
This is because the [`service_registries`](https://www.terraform.io/docs/providers/aws/r/ecs_service.html#service_registries-1) map on object `aws_ecs_service.all` lacks the required arguments `container_name` and `container_port`. Please note that these are not required in general but are required for bridge and host mode.

**Comment by JonRoma** [comment]
Example code isn't part of this repository, and there's no use case that merits attention to this ancient issue.
