### ISSUE TITLE
Need to support execution_role_arn inside task_definition block

### ISSUE THREAD

**Issue by JonRoma** [techservicesillinois/terraform-aws-ecs-service#18]
The ecs_task_definition resource includes a execution_role_arn key that's used to specify the task execution role assumed by the Amazon ECS container agent and Docker daemon. This needs to be exposed to the user of terraform-aws-ecs-service. See https://www.terraform.io/docs/providers/aws/r/ecs_task_definition.html.

This is required to deploy services that use Amazon SSM parameter store.

This feature is required to deploy AuthMan and Course Explorer.

**Comment by ddriddle** [comment]
@JonRoma currently the `execution_role_arn` is hard coded to `ecsTaskExecutionRole`. At this time, I do not think we need to change this. To satisfy the needs for AuthMan and CIS to use SSM, I plan to modify the `ecsTaskExecutionRole` role (See issue: techservicesillinois/as-aws-modules#85).
