### ISSUE TITLE
Testing framework 

### ISSUE THREAD

**Issue by stephencoe** [techservicesillinois/terraform-aws-ecs-service#42]
Hi 👋 

I couldn't find a better place for this to be asked but I  was interested in how you are testing using behave. Is this available somewhere? I can only find the reference to the [pip library](https://github.com/techservicesillinois/terraform-aws-ecs-service/blob/master/test/Dockerfile#L5) but wondered if this was available and documented?

**Comment by JonRoma** [comment]
@stephencoe, sorry that this issue got overlooked. I've asked @evanjtravis, the developer most familiar with the testing aspect of our modules to provide you with a quick answer if possible.

**Comment by JonRoma** [comment]
@stephencoe, I see that @evanjtravis didn't answer this query after I assigned the issue. I think the original intent was for this to be released under open source, but that never happened, and the Behave work dormant, and may not be revived.
