### ISSUE TITLE
IdP discovery service needs two host headers

### ISSUE THREAD

**Issue by JonRoma** [techservicesillinois/terraform-aws-ecs-service#46]
Because there are two published hostnames being used for the IdP discovery service, the `terraform-aws-ecs-service` module needs two listeners on two different host headers. @kwessel and I have proved that this works from the console, but the Terraform module doesn't support this.

Given this issue and #44, it may be necessary to re-engineer the `load_balancer` block to support both use cases.

Today we have:

```
load_balancer = {
  name               = "public2"
  port               = "443"
  container_name     = "wayf"
  container_port     = "80"
  host_header        = "discovery.test.itrust.illinois.edu"
  certificate_domain = "discovery.test.itrust.illinois.edu"
}
```

Possible future version:

```
load_balancer = [
  {
    name               = "public2"
    port               = "443"
    container_name     = "wayf"
    container_port     = "80"
    host_header        = "discovery.test.itrust.illinois.edu"
    certificate_domain = "discovery.test.itrust.illinois.edu"
  },
  {
    name               = "public2"
    port               = "443"
    container_name     = "wayf"
    container_port     = "80"
    host_header        = "discovery.illinois.edu"
    certificate_domain = "discovery.illinois.edu"
  }
]
```

**Comment by JonRoma** [comment]
@ddriddle, this is another issue I mentioned this afternoon.

**Comment by JonRoma** [comment]
We avoided this issue by deploying separate containers, and the extra container is eventually going to get deprecated. I'm therefore closing this.

@kwessel, do you have anything to add?

**Comment by ddriddle** [comment]
@ddriddle and @kwessel did you consider using one certificate and a wildcard in the name? Would something like this work for your use case:

```
load_balancer = [
  {
    name               = "public2"
    port               = "443"
    container_name     = "wayf"
    container_port     = "80"
    host_header        = "discovery*.illinois.edu"
    certificate_domain = "discovery.illinois.edu"
  }
]
```

The certificate would just need to have `discovery.test.itrust.illinois.edu` as an alternative name.
